#!/bin/bash

#SBATCH -J job_name
#SBATCH -p gpu
#SBATCH -o filename_%j.txt
#SBATCH -e filename_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node v100:1
#SBATCH --time=00:45:00

#Load any modules that your program needs
module load deeplearning/2.8.0

#Run your program
python train.py --epochs=100 --epochs2=40 --data_dir='/N/u/deduggi/Carbonate/ELPephant-cropped' --params=hyperparameters/inception.json

#--finetune --restore_latest=latest_weights/20220425-234730-58ffs