#!/bin/bash

#SBATCH -J job_name
#SBATCH -p gpu
#SBATCH -o filename_%j.txt
#SBATCH -e filename_%j.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node v100:1
#SBATCH --time=03:00:00

#Load any modules that your program needs
module load deeplearning/2.8.0

#Run your program
python train.py --epochs=40 --data_dir='/N/u/deduggi/Carbonate/ELPephant-cropped' --finetune --restore_best=best_weights/20220422-123035